name: internet_connectivity_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter: 
    sdk: flutter
  connectivity: ^3.0.6

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

